export const GET_WINES = "GET_WINES";
export const GET_TOP_RATED_WINES = "GET_TOP_RATED_WINES";
export const GET_WINE_NAMES_AND_BRANDS = "GET_WINE_NAMES_AND_BRANDS";
export const FILTER_BY_QUERY = "FILTER_BY_QUERY";
