export const GET_WINES = "GET_WINES";
export const GET_TOP_RATED_WINES = "GET_TOP_RATED_WINES";
export const GET_WINE_DETAIL = "GET_WINE_DETAIL";
export const POST_WINE = "POST_WINE";
export const GET_WINE_NAMES_AND_BRANDS = "GET_WINE_NAMES_AND_BRANDS";
export const FILTER_BY_QUERY = "FILTER_BY_QUERY";
export const SORT_WINES_BY_PRICE = "SORT_WINES_BY_PRICE";
export const SORT_WINES_BY_RATING = "SORT_WINES_BY_RATING";
export const SEARCH_WINES = "SEARCH_WINES";

export const GET_WINE_REVIEWS = "GET_WINE_REVIEWS";

export const ADD_ITEMS_STORAGE = "ADD_ITEMS_STORAGE";
export const ADD_CUANTITY_ITEMS = "ADD_CUANTITY_ITEMS";
export const SUBTRACT_CUANTITY_ITEMS = "SUBTRACT_CUANTITY_ITEMS";
export const GET_ITEMS_STORAGE = "GET_ITEMS_STORAGE";
export const GET_TOTAL_ITEMS = "GET_TOTAL_ITEMS";
export const GET_TOTAL_PRICE = "GET_TOTAL_PRICE";
export const OPEN_CART = "OPEN-CART";
export const CLEAR_ITEM_CART = "CLEAR_ITEM_CART";
export const HANDLE_EMPTY_CART = "HANDLE_EMPTY_CART"

export const LOGIN_USER_WITH_GOOGLE = "LOGIN_USER_WITH_GOOGLE";
export const LOGIN_USER_WITH_FACEBOOK = "LOGIN_USER_WITH_FACEBOOK";
export const LOGIN_USER = "LOGIN_USER";
export const GET_USER_ID = "GET_USER_ID";
export const SHOW_LOGIN_MODAL = "SHOW_LOGIN_MODAL";
export const GET_USER = "GET_USER";

export const CLEAR_DETAIL = "CLEAR_DETAIL";

export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const GET_WISHLIST = "GET_WISHLIST";

export const GET_USER_ORDERS = "GET_USER_ORDERS";
